---

- name: web server setup
  remote_user: vagrant
  become: yes

  hosts:
  - web

  tasks:
  - name: Install packages
    package:
      name: "httpd"
      state: present
  
  - name: Enable and run the service
    service:
      name: "httpd"
      state: started
      enabled: yes

  - name: Git clone a website
    git:
      repo: https://github.com/cloudacademy/static-website-example
      dest: "/var/www/html"
      update: yes

  - name: Set permissions on website correctly
    file: 
      dest: "/var/www/html"
      owner: root
      group: apache
      mode: "u=rwX,g=rX,o=rX"
      recurse: yes
